name: Update Cat gallery

on:
  push:
    branches:
      - main
    paths:
      - 'cats/*.png'
  workflow_dispatch:

permissions: write-all

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - run: python scripts/generate_gallery.py
      
      - run: |
          git config --global user.name "cat-gallery-updater[bot]"
          git config --global user.email "cat-gallery-updater-bot@users.noreply.github.com"
          git add .
          git commit -m "Updated Cat gallery via Cat Gallery Updater bot"
          git push